### ISSUE TITLE
remark fields are limited to 80 chars

### ISSUE THREAD

**Issue by 3nids** [teksi/wastewater#10]
I know that this is the VSA standard but this has proven to be an issue for users and was already discussed in QGEP.
I would recommend avoid such limitation in the data model.

**Comment by ponceta** [comment]
I would propose to be flexible in the datamodel (text field) and to add a warning on the .qgs form of every attribute mentionning that when going over 80 characters, content will be truncated when exporting data to INTERLIS.

Sample possible behaviour :

1. Redlining remark field
2. Hint on what is going wrong
` length("remark") < 80`
"Attention, les remarques textuelles de plus de 80 charactères seront tronquées à l'export. Evaluez les champs appropriés pour saisir toute information pertinente."
4. Possible enforcement of the constraint on QGIS side

![image](https://github.com/teksi/wastewater/assets/8614223/6547920b-f1bd-4e62-b238-6d73ce91f290)

**Comment by ponceta** [comment]
Old issue : https://github.com/QGEP/QGEP/issues/289

**Comment by 3nids** [comment]
Sounds like a good approach to me, let me know if I can implement this.

**Comment by sjib** [comment]
The problem is that you will cut the remarks when exporting to INTERLIS and then you will loose data. You should use  the possibilites to add a file or photo if you need longer documentation for a certain object.

**Comment by sjib** [comment]
Suggestion for implementation: 
Instead of 
`ALTER TABLE tww_od.data_media ADD COLUMN path  varchar(1023) ;`

New:
`ALTER TABLE tww_od.data_media ADD COLUMN path TEXT CHECK(char_length(path)<=1023)`

https://www.postgresqltutorial.com/postgresql-tutorial/postgresql-check-constraint/
and
https://stackoverflow.com/questions/4848964/difference-between-text-and-varchar-character-varying
Would this be a good approach? @ponceta

**Comment by cymed** [comment]
For those users who need the Interlis export, the limitation to 80 characters is extremely useful. Otherwise the remark field gets misused to not fill out attributes in their corresponding fields. As there is no user rights management on the QGIS side, any user can alter permissions - not good.

I like the idea of @sjib to add a check constraint on the text fields on the db side and add two functions `create_textlength_constraint `and `drop_textlength_constraint ` in `tww_sys`

**Comment by 3nids** [comment]
> Instead of
ALTER TABLE tww_od.data_media ADD COLUMN path  varchar(1023) ;
> New:
ALTER TABLE tww_od.data_media ADD COLUMN path TEXT CHECK(char_length(path)<=1023);

this would result in the exact same behavior. CHECK is a hard constraint on the DB side.

**Comment by sjib** [comment]
![20231211_lenght_max_xxx_constraints](https://github.com/teksi/wastewater/assets/1265865/0910afaf-9ca4-4541-a606-5d46d09c14e7)

Here my suggestion with naming length_max_xx_classname_attributename - this then gives a clear error message.

Has to be added in two statements:
`ALTER TABLE test.uuidtest ADD COLUMN classname TEXT;`
`ALTER TABLE test.uuidtest ADD CONSTRAINT length_max_20_uuidtest_classname CHECK(char_length(classname)<=20);`

**Comment by 3nids** [comment]
so who does this?

**Comment by sjib** [comment]
I have prepared - I can make a pull request when ok how it is suggested.

**Comment by 3nids** [comment]
for me it's good, please proceed

**Comment by ponceta** [comment]
Let's try it like this!

In the end, the admin user is always able : 
- to right click and deactivate / soften the constraint
- to right click and change the datatype

What is good with this approach is that we allow some simple flexibility with some recommandation, best practices and warnings about the INTERLIS export feature.

**Comment by sjib** [comment]
> for me it's good, please proceed

@3nids Pull request added - please review
