### ISSUE TITLE
Error in datamodel kek part

### ISSUE THREAD

**Issue by urskaufmann** [teksi/wastewater#224]
- [x] I miss the kek objektkatalog. But I think the field damage_manhole.manhole_channel_distance should be just *.manhole_distance.

- [x] And I wonder, why there is a link in the project - layer-properties vw_tww_damage for damage.single_damage_class. Imo a value relation is enough

**Comment by sjib** [comment]
![20240429_tww_damage_channel_damage_manhole](https://github.com/teksi/wastewater/assets/1265865/52fb32d3-051d-4223-a3a5-97002ac3d4f2)

I had to change the attribute names in these classe to be different to not create problems with PUM (PUM does not support the same attribute names in different subclasses)

**Comment by urskaufmann** [comment]
I do not understand: instead of damage_manhole.manhole_channel_distance just damage_manhole.manhole_distance. manhole_distance is unique in tww_sys.dictionary_od_field

**Comment by sjib** [comment]
Ok, now I understand your point: damage_manhole.manhole_channel_distance should be only damage_manhole.manhole_distance.
That is a typo from my side by adapting from damage_manhole.distance to damage_manhole.manhole_channel_distance instead of damage_manhole.manhole_distance 
to not have a conflict with damage_channel.distance that was also adapted: to  damage_channel.channel_distance

**Comment by sjib** [comment]
Patch with Pull request https://github.com/teksi/wastewater/pull/230

**Comment by ponceta** [comment]
QGIS project issue is fixed in upcoming .qgs project :
![image](https://github.com/teksi/wastewater/assets/8614223/e97791d9-82b0-41db-b8c7-71ff3dc43f43)

https://github.com/teksi/wastewater/pull/196
