### ISSUE TITLE
QGIS project : Reach points are not loaded

### ISSUE THREAD

**Issue by ponceta** [teksi/wastewater#460]
**Describe the bug**
Reach points are not loaded in the QGIS project, therefore if any corrections around these entity is require, the user has to manually add these to the project :

See related issue : https://github.com/teksi/wastewater/issues/459

**Expected behavior**
Reach points are loaded but deactivated by default in the QGIS project.

**Screenshots / data**
If applicable, add screenshots or data to help explain your problem.

**Desktop (please complete the following information):**
 - TWW version
 - QGIS Version
 - OS

**Additional context**
WARNING    Could not export to the interlis schema : Invalid dataowner reference for object 'ch000000RP000012' of type 'haltungspunkt'

**Comment by urskaufmann** [comment]
Reachpoint-attributs are part of vw_tww_reach. Therefore it's not necessary to add reachpoints as layer.
If the default-values for dataowner and provider work correct, then this problem should not happen.
I did not add the fk_dataowner, fk_provider field of the reachpoints to the attributform in the project, because nobody wants to add these (nonsense-)fields. I have once defined a sql to fill these attributs automatic (wastewater-structure -> networkelement -> reachpoint). The user should never have to think about these attributs...

**Comment by ponceta** [comment]
Is it critical if we add this layer?

> If the default-values for dataowner and provider work correct, then this problem should not happen.

I hope we fix it soon but in the meantime it would be really practical to be able to fix issues related to that so users can start using TWW.

**Comment by sjib** [comment]
@ponceta @urskaufmann

Please align your ideas and thoughts on how things are implemented right now – I think there are different conceptions and it would be good to sort these out first, before changing something!

>

**Comment by urskaufmann** [comment]
![image](https://github.com/user-attachments/assets/202bc808-f924-457c-967c-62811f332419)
All reachpoint fields are in tww_vw_reach: between the two red lines in the picture
I did not add the yellow marked fields to the form, because user want/are not allowed not to edit these attributes
But if necessary its easy to add this fields.
Instead of adding a new layer its easier to config/pre-configure this fields in vw_tww_reach.

Remember: in normal manhole case, all reachpoints will be at the same place. You can not easy select the reachpoint of a specific reach. 

It's important to have a function or trigger that sets these fk_dataowner and fk_provider to the similar value of the reach. All other values make no sense (because a reachpoint only exists if the reach exists).

**Comment by ponceta** [comment]
I propose to add this `reach_point` layer mainly to deal with special structures, complex geometries and 3D issues (and to eventually fix issues related to "not working as it should" functions).

This will help us debugging users for the starting period.

It can be deactivated by default and is actually configured to show only under 1:100 scale.

We can easily remove this layer from the project once everything is working as it should.

![image](https://github.com/user-attachments/assets/06663896-de6f-417e-9eaf-d9b5e854f6e2)

**Comment by urskaufmann** [comment]
Ok. I'm sure, some users will try to move reachpoints to edit reach-geometrie and it can also be confusing, that you can edit reachpoint levels in two layers, but you can not connect the reachpoint directly to the wastewater node etc.
There will be issues to this themes...

**Comment by ponceta** [comment]
I removed it from Pull Request as it brings more questions than it solves issues.
