### ISSUE TITLE
organisation explanation

### ISSUE THREAD

**Issue by 3nids** [teksi/wastewater#57]
Can someone explain the idea about handling of organisations?

We have a view which is a 1:1 with the table of the same name. why a view?
Then in the insert/update triggers, it only tries to insert/update the file table (and nothing in organisation)

Current documentation is lacking: https://qgep.github.io/docs/user-guide/layerexplanations/layerexplanation.html#organisations-qgep-od-organisation

**Comment by urskaufmann** [comment]
I think, it's because it was a view in qgep, in DSS version 2015 it was necessary to have a view.

file table: goes in the same direction as my question: https://github.com/teksi/wastewater/discussions/34

**Comment by sjib** [comment]
Organisation in VSA-DSS 2015 had several subclasses (municipality, canton, etc) and needed a view therefore. For exporting VSA-DSS 2015 the relation has to be added by copying the obj_id of the superclass of a dataset to the respective subclass. Else VSA-DSS 2015 INTERLIS export will not work. [An extra check on this was added](https://github.com/QGEP/qgepqwat2ili/blob/46366217582c7c02fb63122efa95f0d9964bcbb9/qgepqwat2ili/utils/ili2db.py#L9).


Organisation in VSA-DSS 2020 was changed an there are no subclasses anymore.
All organisations are maintained centrally by the VSA since the first 2020 release, so that we avoid having duplicates of the same organisations. Interested organisations can easily apply to be added: see https://vsa.ch/fr/fachbereiche-cc/assainissement-urbain/pgee-plan-general-devacuation-des-eaux/gestion-des-donnees/#Tableau-d-associations.

So as described in the cahier des charges there should be an import option also for this data (and then we should discuss and define a selection process so that you do not have to choose from all 2500 existing organisations – something to discuss between opengis and Urs Kaufmann where to place this selection configuration – project file or/and configuration in datamodel tool and maybe additional column needed in class organisation (selected) and/or a new function to download and import only selected organisations from the VSA organisation dataset locally). 

With this mentioned we have no more class organisation datasets within the dss, kek or sia405_abwasser datasets as with release 2015 (qgep) and the users have to first import the organisation dataset and then the rest of the data to have valid foreign keys on the organisation class. This process needs user documentation.

As organisations are defined in the datamodel SIA405_Base_Abwasser_1_LV95 that is imported in all supported import/export models it does not need additional configuration.

The model hierarchies are as follows:
MODEL DSS_2020_1_LV95 (de) AT "http://www.vsa.ch/models"
  VERSION "18.10.2023" = 

  IMPORTS UNQUALIFIED INTERLIS;
  IMPORTS Units;
  IMPORTS Base_LV95;
  IMPORTS SIA405_Base_Abwasser_1_LV95;

MODEL SIA405_ABWASSER_2020_1_LV95 (de) AT "http://www.sia.ch/405"
  VERSION "21.10.2023" = 

  IMPORTS UNQUALIFIED INTERLIS;
  IMPORTS Units;
  IMPORTS Base_LV95;
IMPORTS SIA405_Base_Abwasser_1_LV95;

MODEL VSA_KEK_2020_1_LV95 (de) AT "http://www.vsa.ch/models"
  VERSION "30.10.2023" = 

  IMPORTS UNQUALIFIED INTERLIS;
  IMPORTS Units;
  IMPORTS Base_LV95;
  IMPORTS SIA405_Base_Abwasser_1_LV95;
  IMPORTS SIA405_ABWASSER_2020_1_LV95;

All needed model files are here:
https://www.vsa.ch/models/?dir=2020_1

**Comment by sjib** [comment]
Enhanced documentation for organisation in QGEP suggested https://github.com/QGEP/docs/pull/219

**Comment by sjib** [comment]
Subclass check in INTERLIS export: https://github.com/QGEP/qgepqwat2ili/issues/116#issuecomment-1492563557

**Comment by 3nids** [comment]
Thanks a lot for the info.
So, shall we drop the view?

**Comment by cymed** [comment]
> Thanks a lot for the info. So, shall we drop the view?

Imho yes

**Comment by urskaufmann** [comment]
Yes, in the new project I have just the table
